name: 构建推送

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 1 * *"

jobs:
  caddy:
    runs-on: ubuntu-latest
    steps:
      - name: install curl jq
        run: sudo apt update & sudo apt install -y curl jq

      - name: Set GITHUB_ENV
        run: |
          echo "VERSION=$(curl --silent "https://api.github.com/repos/caddyserver/caddy/releases/latest" | jq -r .tag_name)" >> $GITHUB_ENV
          echo "DOCKER_HUB_TAG=$(curl --silent https://registry.hub.docker.com/v2/repositories/fxtaoo/caddy/tags | jq -r '.results | .[1] | .name')" >> $GITHUB_ENV
          echo "XCADDY_VERSION=$(curl --silent "https://api.github.com/repos/caddyserver/xcaddy/releases/latest" | jq -r .tag_name | sed 's/^v//')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        if: ${{ env.VERSION != env.DOCKER_HUB_TAG }}
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: ${{ env.VERSION != env.DOCKER_HUB_TAG }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: ${{ env.VERSION != env.DOCKER_HUB_TAG }}
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:caddy"
          file: ./Dockerfile
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            XCADDY_VERSION=${{ env.XCADDY_VERSION }}
          tags: |
            fxtaoo/caddy:latest
            fxtaoo/caddy:${{ env.VERSION }}
