name: 构建推送

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 1 * *"

jobs:
  caddy:
    runs-on: ubuntu-latest
    steps:
      - name: install curl jq
        run: sudo apt update & sudo apt install -y curl jq

      - name: Set GITHUB_ENV
        run: |
          echo "CADDY_VERSION=$(curl --silent "https://api.github.com/repos/caddyserver/caddy/releases/latest" | jq -r .tag_name)" >> $GITHUB_ENV
          echo "CADDY_TAG=$(echo ${{ env.CADDY_VERSION }} | sed 's/^v//')" >> $GITHUB_ENV
          echo "DOCKER_HUB_CADDY_VERSION=$(curl --silent https://registry.hub.docker.com/v2/repositories/fxtaoo/caddy/tags | jq -r '.results | .[1] | .name')" >> $GITHUB_ENV
          echo "XCADDY_VERSION=$(curl --silent "https://api.github.com/repos/caddyserver/xcaddy/releases/latest" | jq -r .tag_name | sed 's/^v//')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        if: ${{ env.CADDY_TAG != env.DOCKER_HUB_CADDY_VERSION }}
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: ${{ env.CADDY_TAG != env.DOCKER_HUB_CADDY_VERSION }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: ${{ env.CADDY_TAG != env.DOCKER_HUB_CADDY_VERSION }}
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:caddy"
          file: ./Dockerfile
          push: true
          build-args: |
            XCADDY_VERSION=${{ env.XCADDY_VERSION }}
            CADDY_VERSION=${{ env.CADDY_VERSION }}
          tags: |
            fxtaoo/caddy:latest
            fxtaoo/caddy:${{ env.CADDY_TAG }}

  v2ray:
    runs-on: ubuntu-latest
    steps:
      - name: install curl jq
        run: sudo apt update & sudo apt install -y curl jq

      - name: Set GITHUB_ENV
        run: |
          echo "V2RAY_VERSION=$(curl --silent "https://api.github.com/repos/v2fly/v2ray-core/releases/latest" | jq -r .tag_name)" >> $GITHUB_ENV
          echo "DOCKER_HUB_V2RAY_VERSION=$(curl --silent https://registry.hub.docker.com/v2/repositories/fxtaoo/v2ray/tags | jq -r '.results | .[1] | .name')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        if: ${{ env.V2RAY_VERSION != env.DOCKER_HUB_V2RAY_VERSION }}
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: ${{ env.V2RAY_VERSION != env.DOCKER_HUB_V2RAY_VERSION }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: ${{ env.V2RAY_VERSION != env.DOCKER_HUB_V2RAY_VERSION }}
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:v2ray"
          file: ./Dockerfile
          push: true
          build-args: |
            V2RAY_VERSION=${{ env.V2RAY_VERSION }}
          tags: |
            fxtaoo/v2ray:latest
            fxtaoo/v2ray:${{ env.V2RAY_VERSION }}
